---
name: cortex-debug
description: Visual Studio Code extension for enhancing debug capabilities for Cortex-M Microcontrollers
homepage: https://github.com/Marus/cortex-debug
licenses:
  - MIT
languages:
  - C
  - C++
  - Rust
categories:
  - DAP

source:
  id: pkg:github/Marus/cortex-debug@v1.12.1-pre6
  asset:
    file: cortex-debug-1.12.1-pre6.vsix

share:
  cortex-debug/: extension/
